---
jobs:
  build:
    docker:
      -
        image: "circleci/openjdk:8-jdk"
    environment:
      MAVEN_OPTS: "-Xmx3200m"
    steps:
      - checkout
      -
        restore_cache:
          keys:
            - "v1-dependencies-{{ checksum \"pom.xml\" }}"
            - v1-dependencies-
      -
        run: "mvn dependency:go-offline"
      -
        save_cache:
          key: "v1-dependencies-{{ checksum \"pom.xml\" }}"
          paths:
            - ~/.m2
      -
        run: "mvn integration-test"
    working_directory: ~/repo
  test:
    steps:
      -
        run:
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          name: "Save test results"
          when: "always - asasas - store_test_results path:~/test-results"
version: 2.1
